<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>a0f10732-a16d-45ab-b155-ca3d91fc615a</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Controllers\**" />
    <Content Remove="Controllers\**" />
    <EmbeddedResource Remove="Controllers\**" />
    <None Remove="Controllers\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.Google" Version="8.0.16" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.11">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Ibcraft.Application\Ibcraft.Application.csproj" />
    <ProjectReference Include="..\Ibcraft.DataAccess\Ibcraft.DataAccess.csproj" />
    <ProjectReference Include="..\Ibcraft.Infrastructure\Ibcraft.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="ibcraft.UI\" />
    <Folder Include="static\" />
  </ItemGroup>

</Project>
